In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

# Create 1D array

array1 = np.array([1,2,3,4,5])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
array2 = np.array([1, 2, 3, 4, 5])
array2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [3]:
# 2D array 

array2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(array2)
print(type(array2))
print(array2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
(2, 5)


In [4]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [52]:
print(np.ones((3,4)))
print(np.zeros((2,3)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# Attributes of numpy array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f"Array: {arr}")
print(f"Shape: {arr.shape}")
print(f"Number of dimension: {arr.ndim}")
print(f"Size(number of elements): {arr.size}")
print(f"Data type: {arr.dtype}")
print(f"Item size in bytes: {arr.itemsize}")

Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Number of dimension: 2
Size(number of elements): 10
Data type: int64
Item size in bytes: 8


In [9]:
# Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print(f"Addition: {arr1 + arr2}")
# Element wise subtraction
print(f"Subtraction: {arr1 - arr2}")
# Element wise multiplication
print(f"Multiplication: {arr1 * arr2}")
# Element wise division
print(f"Division: {arr1 / arr2}")

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [10]:
# Universal function
arr = np.array([1, 2, 3, 4, 5])

print(f"{np.sqrt(arr)}")
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [18]:
# Array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(arr[0][0])

1


In [30]:
print(arr[1:,2:])
print(arr[1:,1:3])
print(arr[:2, 1:3])

[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
[[2 3]
 [6 7]]


In [32]:
# Modify the array element

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [38]:
# Statistical concepts-->Normalization
# To have mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
print(f"Mean: {mean}")
std_dev = np.std(data)
print(f"Standard deviation: {std_dev}")
median = np.median(data)
print(f"Median: {median}")
var = np.var(data)
print(f"Variance: {var}")


normalized_data = (data-mean)/std_dev
print(f"Normalized data: {normalized_data}")

Mean: 3.0
Standard deviation: 1.4142135623730951
Median: 3.0
Variance: 2.0
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
# Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])


print(data[(data>4) & (data<8)])

[5 6 7]
