# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [2]:
[[np.random.randint(1, 20) for _ in range(5)] for _ in range(5)]

[[16, 17, 2, 5, 2],
 [2, 15, 4, 11, 4],
 [2, 15, 9, 19, 1],
 [9, 13, 16, 1, 19],
 [13, 1, 12, 19, 3]]

In [3]:
arr = np.array([[np.random.randint(1,20) for _ in range(5)]for _ in range(5)])
arr1 = np.random.randint(1,20, size=(5,5))
print(arr1.shape)
print(f"Original:\n {arr1}")
print(arr.shape)
print(f"Original:\n {arr}")
arr[:,2] = 1
print(f"After: \n{arr}")

(5, 5)
Original:
 [[ 2 16  7 15 10]
 [ 8 12  7  3  6]
 [18  1 19 11 11]
 [15 16 15  8  9]
 [10  1  3 12 17]]
(5, 5)
Original:
 [[ 1 14 19 19 11]
 [ 2 10 15  5  3]
 [15  1  1  6  8]
 [ 1 15  6  7  4]
 [ 2  4 14  4  8]]
After: 
[[ 1 14  1 19 11]
 [ 2 10  1  5  3]
 [15  1  1  6  8]
 [ 1 15  1  7  4]
 [ 2  4  1  4  8]]


In [4]:
arr2 = np.arange(1,17).reshape(4,4)
print(f"Before:\n{arr2}")
print()
print(np.diagonal(arr2,0))
np.fill_diagonal(arr2, 0)
print(f"After: \n{arr2}")

Before:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 1  6 11 16]
After: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr = np.arange(1,37).reshape(6,6)
print(arr)
sub_arr = arr[2:5,1:4]
print(sub_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [6]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
border_arr = np.concatenate((arr[:,0], arr[:,-1], arr[0,:], arr[-1,:]))
print(border_arr)

[[19 14 15  3  2]
 [ 6  8  5 19  3]
 [ 2 16  9  1 19]
 [ 9  2 13 12 20]
 [16  5  4 14  1]]
[19  6  2  9 16  2  3 19 20  1 19 14 15  3  2 16  5  4 14  1]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr1 = np.random.randint(1,13,size=(3,4))
print(arr1)
arr2 = np.random.randint(1,13,size=(3,4))
print(arr2)
print(f"Addition: {arr1+arr2}")
print(f"Subtraction: {arr1-arr2}")
print(f"Multiplication: {arr1*arr2}")
print(f"Division: {arr1/arr2}")

[[ 9  1 11 11]
 [ 5 10  7 12]
 [11  8  9  6]]
[[ 8  9  3 10]
 [ 1  1  1  3]
 [ 1  6  6  7]]
Addition: [[17 10 14 21]
 [ 6 11  8 15]
 [12 14 15 13]]
Subtraction: [[ 1 -8  8  1]
 [ 4  9  6  9]
 [10  2  3 -1]]
Multiplication: [[ 72   9  33 110]
 [  5  10   7  36]
 [ 11  48  54  42]]
Division: [[ 1.125       0.11111111  3.66666667  1.1       ]
 [ 5.         10.          7.          4.        ]
 [11.          1.33333333  1.5         0.85714286]]


In [8]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(np.sum(arr, axis=0))
print(np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40]
[10 26 42 58]
[28 32 36 40]
[10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr = np.random.randint(1,11, size=(5,5))
print(arr)
print(f"Mean: {arr.mean()}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"STD: {arr.std()}")
print(f"STD: {np.std(arr)}")
print(f"Variance: {arr.var()}")
print(f"Variance: {np.var(arr)}")

[[ 6  6  9  4  5]
 [ 5  4  7  4  9]
 [ 6  2  2  1  3]
 [ 8  9  9  5  9]
 [ 8 10  4  2  3]]
Mean: 5.6
Mean: 5.6
Median: 5.0
STD: 2.6532998322843198
STD: 2.6532998322843198
Variance: 7.039999999999999
Variance: 7.039999999999999


In [10]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
mean = np.mean(arr)
std = np.std(arr)
print(f"Normalization:\n {(arr-mean)/std}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalization:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr = np.random.randint(1,10, size=(3,3))
print(f"Before: \n{arr}")
arr1 = np.random.randint(1,4, size=(3,))
print(f"{arr1}")

new = arr + arr1

print(f"After: \n{new}")


Before: 
[[6 9 6]
 [6 8 1]
 [9 6 8]]
[2 2 2]
After: 
[[ 8 11  8]
 [ 8 10  3]
 [11  8 10]]


In [12]:
arr = np.random.randint(1, 10, size=(4, 4))
print(f"Before: \n{arr}")
arr1 = np.random.randint(1, 4, size=(4,))
print(f"{arr1}")

new = arr - arr1

print(f"After: \n{new}")

Before: 
[[2 2 7 8]
 [5 7 9 9]
 [9 7 2 5]
 [9 3 1 3]]
[1 1 1 1]
After: 
[[1 1 6 7]
 [4 6 8 8]
 [8 6 1 4]
 [8 2 0 2]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
arr = np.random.randint(1,11,size=(3,3))
print(f"Array:\n{arr}")
det = np.linalg.det(arr)
inv = np.linalg.inv(arr)
eg = np.linalg.eig(arr)
egv = np.linalg.eigvals(arr)

print(f"Determinanat: \n{det}")
print(f"Inverse: \n{inv}")
print(f"Eigen: \n{eg}")
print(f"Eigen Values: \n{egv}")

Array:
[[ 1  2  1]
 [ 8  3  4]
 [ 7 10  8]]
Determinanat: 
-28.99999999999999
Inverse: 
[[ 0.55172414  0.20689655 -0.17241379]
 [ 1.24137931 -0.03448276 -0.13793103]
 [-2.03448276 -0.13793103  0.44827586]]
Eigen: 
EigResult(eigenvalues=array([13.86822014,  0.78742225, -2.65564238]), eigenvectors=array([[-0.13605275, -0.32064265,  0.27781328],
       [-0.42884009, -0.39611681, -0.78479398],
       [-0.89307661,  0.86039512,  0.55400197]]))
Eigen Values: 
[13.86822014  0.78742225 -2.65564238]


In [14]:
arr1 = np.random.randint(1,4, size=(2,3))
print(arr1)
arr2 = np.random.randint(1, 4, size=(3,2))
print(arr2)

mul = np.linalg.matmul(arr1,arr2)
print(mul)

mul2 = np.dot(arr1, arr2)
print(mul2)


[[3 3 3]
 [2 2 2]]
[[2 2]
 [2 3]
 [2 1]]
[[18 18]
 [12 12]]
[[18 18]
 [12 12]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr1 = arr.reshape(1,9)
print(arr1)
arr2 = arr1.reshape(9,1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [16]:
arr = np.random.randint(1,10, size=(5,5))
print(arr)
arr1 = arr.flatten()
print(arr1)
arr2 = arr1.reshape(5,5)
print(arr2)

[[3 3 6 5 2]
 [4 1 5 6 2]
 [7 8 6 5 2]
 [5 1 1 4 7]
 [3 5 8 9 3]]
[3 3 6 5 2 4 1 5 6 2 7 8 6 5 2 5 1 1 4 7 3 5 8 9 3]
[[3 3 6 5 2]
 [4 1 5 6 2]
 [7 8 6 5 2]
 [5 1 1 4 7]
 [3 5 8 9 3]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
arr = np.random.randint(1,20, size=(5,5))
print(arr)
corner = np.concatenate((arr[0:1, 0], arr[0:1,-1], arr[-1:, 0], arr[-1:,-1]))
corner2 = arr[[0,0,1,1],[0,-1,0,-1]] # ai pair hisebe kaj kore. aikhane pair hobe-->(0,0), (0,-1), (1,0), (1,-1)
print(corner)
print(corner2)

[[11  3 17 16  5]
 [ 2 14 19  5  1]
 [11 13 12 14  7]
 [13 12 19  9  1]
 [18  3 19 15 14]]
[11  5 18 14]
[11  5  2  1]


In [18]:
arr = np.random.randint(1, 20, size=(4, 4))
print(arr)
arr[arr>10] = 10
print(arr)

[[18  4  2  9]
 [11  5  5 18]
 [ 1  1  2  4]
 [ 3 15  3 14]]
[[10  4  2  9]
 [10  5  5 10]
 [ 1  1  2  4]
 [ 3 10  3 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [29]:
data_type = [("name","U10"), ("age", "i4"), ("weight", "f4")]
data = np.array([("Samin", 25, 57.5), ("Tanzil", 46, 56), ("Masud", 28, 65)], dtype=data_type)
print(data)
sorted_data = np.sort(data, order="age")
print(sorted_data)

[('Samin', 25, 57.5) ('Tanzil', 46, 56. ) ('Masud', 28, 65. )]
[('Samin', 25, 57.5) ('Masud', 28, 65. ) ('Tanzil', 46, 56. )]


In [45]:
data_type = [("x", "i4"), ("y", "i4")]
data = np.array([(1,2), (3,4), (5,6)], dtype=data_type)
print(data)
dis = np.sqrt((data["x"][:,np.newaxis]-data["x"])**2 + (data["y"][:,np.newaxis]-data["y"])**2)
print(dis)

[(1, 2) (3, 4) (5, 6)]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [50]:
import numpy.ma as ma
arr_or = np.random.randint(1,21,size=(4,4))
print(arr_or)
arr_ma = ma.masked_greater(arr_or, 10)
print(arr_ma)
sum_unmasked = arr_ma.sum()
print(sum_unmasked)

[[14 12 17 14]
 [ 8 13 14 17]
 [ 7 16  6  2]
 [15 15  8 16]]
[[-- -- -- --]
 [8 -- -- --]
 [7 -- 6 2]
 [-- -- 8 --]]
31


In [67]:
arr = np.random.randint(1,21,size=(3,3))
print(arr)

x = ma.masked_array(arr,mask=arr>=10)
print(x)
mas = ma.masked_array(arr,mask=np.eye(3,dtype=bool))
print(mas)
mean = np.mean(mas)
print(mean)
fill = mas.filled(mean)
print(fill)

[[ 9  3  5]
 [ 6 12 12]
 [20  9  5]]
[[9 3 5]
 [6 -- --]
 [-- 9 5]]
[[-- 3 5]
 [6 -- 12]
 [20 9 --]]
9.166666666666666
[[ 9  3  5]
 [ 6  9 12]
 [20  9  9]]
